# Generated by Django 3.0.6 on 2020-06-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Traveller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='offer_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
